/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onitama;

/**
 *
 * @author antoi
 */
public class fenetreDeJeu extends javax.swing.JFrame {

    /**
     * Creates new form fenetreDeJeu
     */
    public fenetreDeJeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauGrille = new javax.swing.JPanel();
        carteJoueur1 = new javax.swing.JPanel();
        carteJoueur2 = new javax.swing.JPanel();
        carteEchiquier = new javax.swing.JPanel();
        panneauInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelJ1 = new javax.swing.JTextField();
        labelJ2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneauGrille.setBackground(new java.awt.Color(255, 255, 255));
        panneauGrille.setLayout(new java.awt.GridLayout(5, 5));
        getContentPane().add(panneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 700, 700));

        carteJoueur1.setBackground(new java.awt.Color(255, 255, 255));
        carteJoueur1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(carteJoueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, 300, 173));

        carteJoueur2.setBackground(new java.awt.Color(255, 255, 255));
        carteJoueur2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(carteJoueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, 300, 173));

        carteEchiquier.setBackground(new java.awt.Color(255, 255, 255));
        carteEchiquier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(carteEchiquier, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 300, 300, 173));

        panneauInfo.setBackground(new java.awt.Color(51, 204, 255));
        panneauInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom Joueur 1 :");
        panneauInfo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jLabel2.setText("Nom Joueur 2 :");
        panneauInfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        labelJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelJ1ActionPerformed(evt);
            }
        });
        panneauInfo.add(labelJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, -1));
        panneauInfo.add(labelJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, -1));

        jButton1.setText("Démarrer la partie");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panneauInfo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        getContentPane().add(panneauInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 550, 250));

        setBounds(0, 0, 1414, 787);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void labelJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelJ1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel carteEchiquier;
    private javax.swing.JPanel carteJoueur1;
    private javax.swing.JPanel carteJoueur2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField labelJ1;
    private javax.swing.JTextField labelJ2;
    private javax.swing.JPanel panneauGrille;
    private javax.swing.JPanel panneauInfo;
    // End of variables declaration//GEN-END:variables
}
